### ISSUE TITLE
Time Triggered Automation Error

### ISSUE THREAD

**Issue by Epod** [williamlmao/plaid-to-gsheets#2]
Greetings, 

In following the guide to setup the Time Triggered automation in sheets, the job fails to run

```
Exception: Cannot call SpreadsheetApp.getUi() from this context.
    at [unknown function](config:132:27)
```

**Comment by superkeyor** [comment]
Reason:
SpreadsheetApp.getUi() cannot be called by a timer trigger

Fix: 
1) remove const ui = SpreadsheetApp.getUi(); from config.gs
2) change utils.gs by adding const ui = SpreadsheetApp.getUi(); to onOpen
const onOpen = () => {
  const ui = SpreadsheetApp.getUi();
  ui.createMenu("Plaid API Ingest")
    .addItem("Import Latest Transactions", "importLatest")
    .addItem("Import Date Range", "importByDateRange")
    .addItem("Set up", "setUp")
    .addToUi();
};

I am not quite familiar with the syntax, but this fix seems to work 😀 Thank the author of this repo for his tremendous work!

**Comment by williamlmao** [comment]
This has been fixed. Thanks @jerryzhujian9!

**Comment by aeble12** [comment]
Good evening. I'm receiving the same error after setting up the time-based trigger.
