### ISSUE TITLE
Chase now requires OAuth

### ISSUE THREAD

**Issue by wehbs** [williamlmao/plaid-to-gsheets#3]
Is there a way to setup Oauth with Chase for this setup? I lost access to my chase account now that they force the Oauth login.

**Comment by williamlmao** [comment]
Hey @wehbs, thanks for calling this out. My chase login started failing as well. Unfortunately I'm pretty busy right now so not sure when I will be able to get to this, but hoping to update within a month.

**Comment by wehbs** [comment]
@williamlmao Thanks for the reply. I just got approved for production access in Plaid which is part of the necessary steps to get Oauth for Chase enabled. Just waiting for Chase to approve. Once they do I will try to implement and if I get it to work I'll share here. Thanks again for your work on this!

**Comment by williamlmao** [comment]
On second thought, since this repo currently just uses an access token that you already have, I'm not sure that this repo will actually need much updating as it does not handle the plaid link. 

It looks like we're still able to retrieve an access_token based on the code below, but I'm not sure if it will work any differently now. 

@wehbs, please keep us updated on what you find out!


```
import { usePlaidLink } from 'react-plaid-link';
const OAuthLink = () => {
  // The Link token from the first Link initialization
  const linkToken = localStorage.getItem('link_token');
  const onSuccess = React.useCallback((public_token: string) => {
    // send public_token to server, retrieve access_token and item_id
    // return to "https://example.com" upon completion
  });
  const onExit = (err, metadata) => {
    // handle error...
  };
  const config: Parameters<typeof usePlaidLink>[0] = {
    token: linkToken!,
    receivedRedirectUri: window.location.href, //the redirect URI with an OAuth state ID parameter
    onSuccess,
    onExit,
  };
  const { open, ready, error } = usePlaidLink(config);
  // automatically reinitialize Link
  useEffect(() => {
    if (ready) {
      open();
    }
  }, [ready, open]);
  return <></>;
};
export default OAuthLink;
```

**Comment by wehbs** [comment]
@williamlmao yes, that's what I'm thinking as well. I suppose the only thing needing update would be to add the Oauth implementation for chase in the Plaid Quick Start app.

**Comment by wehbs** [comment]
https://github.com/plaid/quickstart#testing-oauth. Looks like this may do it.

**Comment by williamlmao** [comment]
@wehbs Did you see this in the security questionare email?

> 1 more step for OAuth: Submit your [Security Questionnaire](https://dashboard.plaid.com/overview/questionnaire) within 30 days for access to Chase OAuth:
> For now, you'll have access to the non-OAuth flow for Chase in Development and Production. Failure to submit within 30 days may result in Chase becoming temporarily unavailable until the Security Questionnaire has been submitted.

It sounds like there is still a non-OAuth flow that can be used for Chase?

**Comment by wehbs** [comment]
@williamlmao I did but I think that message may be outdated. I wrote in to Plaid support about it and this was a part of their reply:

> In the interest of this pursuit towards a more secure and collaborative financial ecosystem, we are fully deprecating our legacy Chase ins_3 integration on June 30th, 2022. Starting on this date, all Chase traffic will go through our Chase OAuth ins_56 integration, which uses Chase’s secure API to enable safer and more reliable connections between Plaid and Chase.

Although my login through the other flow lasted beyond June 30th.

**Comment by wehbs** [comment]
After many failed attempts I finally got up it back up after Chase approved me for Oauth today! You were right no changes were needed to your code, I just had to make small changes to the quickstart app but it wasn't very straight forward. I'm back in business! Thanks again for your work on this.

**Comment by williamlmao** [comment]
@wehbs amazing! I have been approved for production but Chase has yet to approve me for OAuth. The survey was kind of intense and I wasn't sure how to answer it as I am just using it for personal use, which it seems it is not intended for. How did you answer the questions?

Was it easy to make that change in the quickstart app following the documentation? Would hugely appreciate it if you are able to put in a pull request adding the uodated version of the quickstart app into this repo, or even add it as a standalone.

**Comment by wehbs** [comment]
@williamlmao yea agreed, I just imagined myself creating an app using plaid and answered as best and as honest as I could given how I have things set up.

Yes, not bad at all. I will try and put in th PR tonight. I've made some other changes to you may want to consider merging. For example removing your filter to remove pending transactions from getting imported and added a function in utils.gs to delete those pendings once the posted version is present. I'll submit for review.

Also, have you ever considered creating a google sheet add on for this? I've tried so many financial tracking apps and google sheet add ons but none seem to have all the features in one that I'm looking for. But I've been able to make that happen with this repo. I'd be happy to help with that project if it's something you'd consider.

**Comment by williamlmao** [comment]
@wehbs nice, that's the approach I took as well. It's been 6 days and I haven't heard back about the Chase approval yet. In what form did that notification come for you?

I'm definitely open to putting this out as an add-on, but I'm not super experienced in that realm. I would imagine we'd need to use Plaid more officially, i.e actually building a frontend for users to use Link, and not sure if there are any other hoops to jump through to get it through the approval process. I'm going to reach out to you via email, maybe we can jump on a call to discuss what we'd need to do?

Thank you for all your help on this and appreciate you submitting the PRs!

**Comment by wehbs** [comment]
@williamlmao They actually didn't notify me at all but I kept checking this page https://dashboard.plaid.com/team/oauth-institutions until it said enabled.

Sweet! Yea, please email me (shamirwehbe@gmail.com) this could be a fun side project to work on and we could also help some peeps along the way as what you've done already has helped me and others!

I'll submit some additional PRs soon as I can.
