### ISSUE TITLE
Income marked as negative numbers (how to change)?

### ISSUE THREAD

**Issue by lecoffeeguy** [williamlmao/plaid-to-gsheets#7]
Hi there,

I've connected my account (Dutch bank account), however, credited amounts are marked as positive numbers and debited amount are marked as negative numbers. I´d like to turn this around. How do I do that?

Thanks!

**Comment by lecoffeeguy** [comment]
I checked with Plaid and this is how the data is recovered through the API. I´ve solved this by adapting the google sheet.

**Comment by aeble12** [comment]
Good evening. I've also observed a flipping of positive and negative for debits and credits.
