### ISSUE TITLE
Will code as-is work with credit cards or only bank accounts

### ISSUE THREAD

**Issue by aeble12** [williamlmao/plaid-to-gsheets#8]
Good evening. I've got this up and running with a couple of bank accounts that have access tokens that have been generated with respect to the Plaid "auth" product. I've been tinkering trying to see if I can get this to work with credit card accounts, but have been unsuccessful so far. I think credit cards require a different kind of Plaid product (not "auth" product). I got an access token generated with respect to Plaid's "transactions" product for one of my credit cards so I could  test it in the Google Apps script. I got an error when I ran the Google Apps Script with the test credit card account/access token generated  with respect to Plaid "transactions" product. I was thinking that maybe I need to add more than the access code for the "transactions" product? Or maybe the script as currently written only supports adding accounts that use access tokens that are generated with respect to Plaid's "auth" product (and nothing else). Not sure.  I'm curious if you know off hand if the Google Script, as written, is supposed to work with credit card accounts/access codes generated not with respect to "auth" product (or if that's a totally different animal)?

**Comment by williamlmao** [comment]
You need to make sure the transactions product is enabled via environment
variable in your quickstart/node directory! Should be a variable called
PLAID_PRODUCTS. Make sure transactions is listed.

**Comment by aeble12** [comment]
Thanks for your reply. My issue turned out to be a silly mistake on my part.
