### ISSUE TITLE
Cannot grant permissions

### ISSUE THREAD

**Issue by bryce-hoehn** [williamlmao/plaid-to-gsheets#9]
Hi, I am really interested in running this script and I got through the Plaid quickstart and updated the config.gs script with my bank info. However when I try to run the script I cannot seem to grant it permission to run. 

First I get this error that Google hasn't verified the app.
![image](https://user-images.githubusercontent.com/1351017/216750178-5ca969ce-2ad6-4120-8c16-c2376c89c727.png)

Upon pressing Advanced -> "Go to Plaid API to Google Sheets (unsafe)" I am getting another error message saying "Something went wrong. Please try again"
![image](https://user-images.githubusercontent.com/1351017/216750237-ca40c13a-c96f-464b-997d-fc5db4c5e720.png)

I cannot find any documentation anywhere about what might be causing the "Something went wrong" error. Any help would be appreciated.

**Comment by williamlmao** [comment]
Hey @17hoehbr, I have never seen this and looks like it probably has more to do with something on the google side than this script itsself. I would just try again later. Let me know if its still an issue, but you'll have to give me a little more information to try and troubleshoot and will need you to add me to your sheet so I can try myself.

**Comment by bryce-hoehn** [comment]
I think I figured it out, turns out the issue was being caused by the ClearURLs extension in Firefox. Temporarily disabling the extension fixes the issue.
